-- Legacy placeholder kept only so old references do not break.
--
-- SyncSpace no longer uses Supabase Auth/RLS as the application authority.
-- The canonical schema is under server/migrations:
--
--   server/migrations/0001_*.sql ... 0016_external_agent_accounts.sql
--
-- Current auth model:
--   - internal agents: agents + agent_tokens
--   - external A2A agents: remote_agents + remote_agent_tokens
--   - ownership/membership: participants + workspace_members
--
-- Do not copy the old auth.users/RLS template when adding new schema.
